# This file is auto-generated by @nixcord/nix-generator
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  base = [
    "programs"
    "nixcord"
    "config"
    "plugins"
  ];
in
{
  imports = [
    # Anammox -> Declutter
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "alwaysShowUsername"
      ];
      to = base ++ [
        "declutter"
        "alwaysShowUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "enable"
      ];
      to = base ++ [
        "declutter"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeAudioMenus"
      ];
      to = base ++ [
        "declutter"
        "removeAudioMenus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeAvatarDecoration"
      ];
      to = base ++ [
        "declutter"
        "removeAvatarDecoration"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeBillingSettings"
      ];
      to = base ++ [
        "declutter"
        "removeBillingSettings"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeButtonTooltips"
      ];
      to = base ++ [
        "declutter"
        "removeButtonTooltips"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeClanTag"
      ];
      to = base ++ [
        "declutter"
        "removeClanTag"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeGiftButton"
      ];
      to = base ++ [
        "declutter"
        "removeGiftButton"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeNameplate"
      ];
      to = base ++ [
        "declutter"
        "removeNameplate"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeProfileEffect"
      ];
      to = base ++ [
        "declutter"
        "removeProfileEffect"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeQuestsAboveDM"
      ];
      to = base ++ [
        "declutter"
        "removeQuestsAboveDM"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeServerBoostInfo"
      ];
      to = base ++ [
        "declutter"
        "removeServerBoostInfo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeShopAboveDM"
      ];
      to = base ++ [
        "declutter"
        "removeShopAboveDM"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "anammox"
        "removeUnavailableEmojiPicker"
      ];
      to = base ++ [
        "declutter"
        "removeUnavailableEmojiPicker"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # AudioBookShelfRichPresence -> RichPresence
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "absEnabled"
      ];
      to = base ++ [
        "richPresence"
        "absEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "absPassword"
      ];
      to = base ++ [
        "richPresence"
        "absPassword"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "absServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "absServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "absUsername"
      ];
      to = base ++ [
        "richPresence"
        "absUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "enable"
      ];
      to = base ++ [
        "richPresence"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "enabled"
      ];
      to = base ++ [
        "richPresence"
        "enabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "grEnabled"
      ];
      to = base ++ [
        "richPresence"
        "grEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "grRefreshInterval"
      ];
      to = base ++ [
        "richPresence"
        "grRefreshInterval"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfApiKey"
      ];
      to = base ++ [
        "richPresence"
        "jfApiKey"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfCoverType"
      ];
      to = base ++ [
        "richPresence"
        "jfCoverType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfCustomName"
      ];
      to = base ++ [
        "richPresence"
        "jfCustomName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfEnabled"
      ];
      to = base ++ [
        "richPresence"
        "jfEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfEpisodeFormat"
      ];
      to = base ++ [
        "richPresence"
        "jfEpisodeFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfNameDisplay"
      ];
      to = base ++ [
        "richPresence"
        "jfNameDisplay"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfOverrideType"
      ];
      to = base ++ [
        "richPresence"
        "jfOverrideType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfPrivacyMode"
      ];
      to = base ++ [
        "richPresence"
        "jfPrivacyMode"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "jfServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfShowEpisodeName"
      ];
      to = base ++ [
        "richPresence"
        "jfShowEpisodeName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfShowPausedState"
      ];
      to = base ++ [
        "richPresence"
        "jfShowPausedState"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "jfUserId"
      ];
      to = base ++ [
        "richPresence"
        "jfUserId"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbEnabled"
      ];
      to = base ++ [
        "richPresence"
        "lbEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbHideWithActivity"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithActivity"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbMbContact"
      ];
      to = base ++ [
        "richPresence"
        "lbMbContact"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "lbMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "lbNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbShareSong"
      ];
      to = base ++ [
        "richPresence"
        "lbShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbStatusName"
      ];
      to = base ++ [
        "richPresence"
        "lbStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "lbUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbUseLogo"
      ];
      to = base ++ [
        "richPresence"
        "lbUseLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbUseTimeBar"
      ];
      to = base ++ [
        "richPresence"
        "lbUseTimeBar"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "lbUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmAlwaysHideArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmAlwaysHideArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmEnabled"
      ];
      to = base ++ [
        "richPresence"
        "sfmEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmHideWithExternalRpc"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithExternalRpc"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "sfmNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmShareSong"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmShowLogo"
      ];
      to = base ++ [
        "richPresence"
        "sfmShowLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmStatusName"
      ];
      to = base ++ [
        "richPresence"
        "sfmStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "sfmUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "sfmUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "audioBookShelfRichPresence"
        "tosuEnabled"
      ];
      to = base ++ [
        "richPresence"
        "tosuEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # BetterQuickReact -> MoreQuickReactions
    (lib.modules.doRename {
      from = base ++ [
        "betterQuickReact"
        "columns"
      ];
      to = base ++ [
        "moreQuickReactions"
        "columns"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterQuickReact"
        "compactMode"
      ];
      to = base ++ [
        "moreQuickReactions"
        "compactMode"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterQuickReact"
        "enable"
      ];
      to = base ++ [
        "moreQuickReactions"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterQuickReact"
        "frequentEmojis"
      ];
      to = base ++ [
        "moreQuickReactions"
        "frequentEmojis"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterQuickReact"
        "reactionCount"
      ];
      to = base ++ [
        "moreQuickReactions"
        "reactionCount"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterQuickReact"
        "rows"
      ];
      to = base ++ [
        "moreQuickReactions"
        "rows"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterQuickReact"
        "scroll"
      ];
      to = base ++ [
        "moreQuickReactions"
        "scroll"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # BetterUserArea -> Declutter
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "alwaysShowUsername"
      ];
      to = base ++ [
        "declutter"
        "alwaysShowUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "enable"
      ];
      to = base ++ [
        "declutter"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeAudioMenus"
      ];
      to = base ++ [
        "declutter"
        "removeAudioMenus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeAvatarDecoration"
      ];
      to = base ++ [
        "declutter"
        "removeAvatarDecoration"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeBillingSettings"
      ];
      to = base ++ [
        "declutter"
        "removeBillingSettings"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeButtonTooltips"
      ];
      to = base ++ [
        "declutter"
        "removeButtonTooltips"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeClanTag"
      ];
      to = base ++ [
        "declutter"
        "removeClanTag"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeGiftButton"
      ];
      to = base ++ [
        "declutter"
        "removeGiftButton"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeNameplate"
      ];
      to = base ++ [
        "declutter"
        "removeNameplate"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeProfileEffect"
      ];
      to = base ++ [
        "declutter"
        "removeProfileEffect"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeQuestsAboveDM"
      ];
      to = base ++ [
        "declutter"
        "removeQuestsAboveDM"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeServerBoostInfo"
      ];
      to = base ++ [
        "declutter"
        "removeServerBoostInfo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeShopAboveDM"
      ];
      to = base ++ [
        "declutter"
        "removeShopAboveDM"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "betterUserArea"
        "removeUnavailableEmojiPicker"
      ];
      to = base ++ [
        "declutter"
        "removeUnavailableEmojiPicker"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # EmoteCloner -> ExpressionCloner
    (lib.modules.doRename {
      from = base ++ [
        "emoteCloner"
        "enable"
      ];
      to = base ++ [
        "expressionCloner"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # FriendCloud -> MoreCommands
    (lib.modules.doRename {
      from = base ++ [
        "friendCloud"
        "addFreakyEnding"
      ];
      to = base ++ [
        "moreCommands"
        "addFreakyEnding"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "friendCloud"
        "enable"
      ];
      to = base ++ [
        "moreCommands"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "friendCloud"
        "uwuEveryMessage"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEveryMessage"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "friendCloud"
        "uwuEverything"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEverything"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # GensokyoRadioRPC -> RichPresence
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "absEnabled"
      ];
      to = base ++ [
        "richPresence"
        "absEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "absPassword"
      ];
      to = base ++ [
        "richPresence"
        "absPassword"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "absServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "absServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "absUsername"
      ];
      to = base ++ [
        "richPresence"
        "absUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "enable"
      ];
      to = base ++ [
        "richPresence"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "enabled"
      ];
      to = base ++ [
        "richPresence"
        "enabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "grEnabled"
      ];
      to = base ++ [
        "richPresence"
        "grEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "grRefreshInterval"
      ];
      to = base ++ [
        "richPresence"
        "grRefreshInterval"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfApiKey"
      ];
      to = base ++ [
        "richPresence"
        "jfApiKey"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfCoverType"
      ];
      to = base ++ [
        "richPresence"
        "jfCoverType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfCustomName"
      ];
      to = base ++ [
        "richPresence"
        "jfCustomName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfEnabled"
      ];
      to = base ++ [
        "richPresence"
        "jfEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfEpisodeFormat"
      ];
      to = base ++ [
        "richPresence"
        "jfEpisodeFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfNameDisplay"
      ];
      to = base ++ [
        "richPresence"
        "jfNameDisplay"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfOverrideType"
      ];
      to = base ++ [
        "richPresence"
        "jfOverrideType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfPrivacyMode"
      ];
      to = base ++ [
        "richPresence"
        "jfPrivacyMode"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "jfServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfShowEpisodeName"
      ];
      to = base ++ [
        "richPresence"
        "jfShowEpisodeName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfShowPausedState"
      ];
      to = base ++ [
        "richPresence"
        "jfShowPausedState"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "jfUserId"
      ];
      to = base ++ [
        "richPresence"
        "jfUserId"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbEnabled"
      ];
      to = base ++ [
        "richPresence"
        "lbEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbHideWithActivity"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithActivity"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbMbContact"
      ];
      to = base ++ [
        "richPresence"
        "lbMbContact"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "lbMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "lbNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbShareSong"
      ];
      to = base ++ [
        "richPresence"
        "lbShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbStatusName"
      ];
      to = base ++ [
        "richPresence"
        "lbStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "lbUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbUseLogo"
      ];
      to = base ++ [
        "richPresence"
        "lbUseLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbUseTimeBar"
      ];
      to = base ++ [
        "richPresence"
        "lbUseTimeBar"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "lbUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmAlwaysHideArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmAlwaysHideArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmEnabled"
      ];
      to = base ++ [
        "richPresence"
        "sfmEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmHideWithExternalRpc"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithExternalRpc"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "sfmNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmShareSong"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmShowLogo"
      ];
      to = base ++ [
        "richPresence"
        "sfmShowLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmStatusName"
      ];
      to = base ++ [
        "richPresence"
        "sfmStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "sfmUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "sfmUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "GensokyoRadioRPC"
        "tosuEnabled"
      ];
      to = base ++ [
        "richPresence"
        "tosuEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # GifRoulette -> MoreCommands
    (lib.modules.doRename {
      from = base ++ [
        "gifRoulette"
        "addFreakyEnding"
      ];
      to = base ++ [
        "moreCommands"
        "addFreakyEnding"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "gifRoulette"
        "enable"
      ];
      to = base ++ [
        "moreCommands"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "gifRoulette"
        "uwuEveryMessage"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEveryMessage"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "gifRoulette"
        "uwuEverything"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEverything"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # HideAttachments -> HideMedia
    (lib.modules.doRename {
      from = base ++ [
        "hideAttachments"
        "enable"
      ];
      to = base ++ [
        "hideMedia"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # ImgToGif -> MoreCommands
    (lib.modules.doRename {
      from = base ++ [
        "imgToGif"
        "addFreakyEnding"
      ];
      to = base ++ [
        "moreCommands"
        "addFreakyEnding"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "imgToGif"
        "enable"
      ];
      to = base ++ [
        "moreCommands"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "imgToGif"
        "uwuEveryMessage"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEveryMessage"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "imgToGif"
        "uwuEverything"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEverything"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # JellyfinRichPresence -> RichPresence
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "absEnabled"
      ];
      to = base ++ [
        "richPresence"
        "absEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "absPassword"
      ];
      to = base ++ [
        "richPresence"
        "absPassword"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "absServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "absServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "absUsername"
      ];
      to = base ++ [
        "richPresence"
        "absUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "enable"
      ];
      to = base ++ [
        "richPresence"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "enabled"
      ];
      to = base ++ [
        "richPresence"
        "enabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "grEnabled"
      ];
      to = base ++ [
        "richPresence"
        "grEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "grRefreshInterval"
      ];
      to = base ++ [
        "richPresence"
        "grRefreshInterval"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfApiKey"
      ];
      to = base ++ [
        "richPresence"
        "jfApiKey"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfCoverType"
      ];
      to = base ++ [
        "richPresence"
        "jfCoverType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfCustomName"
      ];
      to = base ++ [
        "richPresence"
        "jfCustomName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfEnabled"
      ];
      to = base ++ [
        "richPresence"
        "jfEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfEpisodeFormat"
      ];
      to = base ++ [
        "richPresence"
        "jfEpisodeFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfNameDisplay"
      ];
      to = base ++ [
        "richPresence"
        "jfNameDisplay"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfOverrideType"
      ];
      to = base ++ [
        "richPresence"
        "jfOverrideType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfPrivacyMode"
      ];
      to = base ++ [
        "richPresence"
        "jfPrivacyMode"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "jfServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfShowEpisodeName"
      ];
      to = base ++ [
        "richPresence"
        "jfShowEpisodeName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfShowPausedState"
      ];
      to = base ++ [
        "richPresence"
        "jfShowPausedState"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "jfUserId"
      ];
      to = base ++ [
        "richPresence"
        "jfUserId"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbEnabled"
      ];
      to = base ++ [
        "richPresence"
        "lbEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbHideWithActivity"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithActivity"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbMbContact"
      ];
      to = base ++ [
        "richPresence"
        "lbMbContact"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "lbMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "lbNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbShareSong"
      ];
      to = base ++ [
        "richPresence"
        "lbShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbStatusName"
      ];
      to = base ++ [
        "richPresence"
        "lbStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "lbUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbUseLogo"
      ];
      to = base ++ [
        "richPresence"
        "lbUseLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbUseTimeBar"
      ];
      to = base ++ [
        "richPresence"
        "lbUseTimeBar"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "lbUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmAlwaysHideArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmAlwaysHideArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmEnabled"
      ];
      to = base ++ [
        "richPresence"
        "sfmEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmHideWithExternalRpc"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithExternalRpc"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "sfmNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmShareSong"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmShowLogo"
      ];
      to = base ++ [
        "richPresence"
        "sfmShowLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmStatusName"
      ];
      to = base ++ [
        "richPresence"
        "sfmStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "sfmUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "sfmUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "jellyfinRichPresence"
        "tosuEnabled"
      ];
      to = base ++ [
        "richPresence"
        "tosuEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # ListenBrainzRPC -> RichPresence
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "absEnabled"
      ];
      to = base ++ [
        "richPresence"
        "absEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "absPassword"
      ];
      to = base ++ [
        "richPresence"
        "absPassword"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "absServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "absServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "absUsername"
      ];
      to = base ++ [
        "richPresence"
        "absUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "enable"
      ];
      to = base ++ [
        "richPresence"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "enabled"
      ];
      to = base ++ [
        "richPresence"
        "enabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "grEnabled"
      ];
      to = base ++ [
        "richPresence"
        "grEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "grRefreshInterval"
      ];
      to = base ++ [
        "richPresence"
        "grRefreshInterval"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfApiKey"
      ];
      to = base ++ [
        "richPresence"
        "jfApiKey"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfCoverType"
      ];
      to = base ++ [
        "richPresence"
        "jfCoverType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfCustomName"
      ];
      to = base ++ [
        "richPresence"
        "jfCustomName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfEnabled"
      ];
      to = base ++ [
        "richPresence"
        "jfEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfEpisodeFormat"
      ];
      to = base ++ [
        "richPresence"
        "jfEpisodeFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfNameDisplay"
      ];
      to = base ++ [
        "richPresence"
        "jfNameDisplay"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfOverrideType"
      ];
      to = base ++ [
        "richPresence"
        "jfOverrideType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfPrivacyMode"
      ];
      to = base ++ [
        "richPresence"
        "jfPrivacyMode"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "jfServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfShowEpisodeName"
      ];
      to = base ++ [
        "richPresence"
        "jfShowEpisodeName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfShowPausedState"
      ];
      to = base ++ [
        "richPresence"
        "jfShowPausedState"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "jfUserId"
      ];
      to = base ++ [
        "richPresence"
        "jfUserId"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbEnabled"
      ];
      to = base ++ [
        "richPresence"
        "lbEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbHideWithActivity"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithActivity"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbMbContact"
      ];
      to = base ++ [
        "richPresence"
        "lbMbContact"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "lbMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "lbNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbShareSong"
      ];
      to = base ++ [
        "richPresence"
        "lbShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbStatusName"
      ];
      to = base ++ [
        "richPresence"
        "lbStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "lbUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbUseLogo"
      ];
      to = base ++ [
        "richPresence"
        "lbUseLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbUseTimeBar"
      ];
      to = base ++ [
        "richPresence"
        "lbUseTimeBar"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "lbUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmAlwaysHideArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmAlwaysHideArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmEnabled"
      ];
      to = base ++ [
        "richPresence"
        "sfmEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmHideWithExternalRpc"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithExternalRpc"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "sfmNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmShareSong"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmShowLogo"
      ];
      to = base ++ [
        "richPresence"
        "sfmShowLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmStatusName"
      ];
      to = base ++ [
        "richPresence"
        "sfmStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "sfmUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "sfmUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "ListenBrainzRPC"
        "tosuEnabled"
      ];
      to = base ++ [
        "richPresence"
        "tosuEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # MemberListActivities -> BetterActivities
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "allActivitiesStyle"
      ];
      to = base ++ [
        "betterActivities"
        "allActivitiesStyle"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "enable"
      ];
      to = base ++ [
        "betterActivities"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "hideTooltip"
      ];
      to = base ++ [
        "betterActivities"
        "hideTooltip"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "iconSize"
      ];
      to = base ++ [
        "betterActivities"
        "iconSize"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "memberList"
      ];
      to = base ++ [
        "betterActivities"
        "memberList"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "removeGameActivityStatus"
      ];
      to = base ++ [
        "betterActivities"
        "removeGameActivityStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "renderGifs"
      ];
      to = base ++ [
        "betterActivities"
        "renderGifs"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "specialFirst"
      ];
      to = base ++ [
        "betterActivities"
        "specialFirst"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "memberListActivities"
        "userPopout"
      ];
      to = base ++ [
        "betterActivities"
        "userPopout"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # MessageTags -> CustomCommands
    (lib.modules.doRename {
      from = base ++ [
        "messageTags"
        "enable"
      ];
      to = base ++ [
        "customCommands"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "messageTags"
        "tagsList"
      ];
      to = base ++ [
        "customCommands"
        "tagsList"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # MoreKaomoji -> MoreCommands
    (lib.modules.doRename {
      from = base ++ [
        "moreKaomoji"
        "addFreakyEnding"
      ];
      to = base ++ [
        "moreCommands"
        "addFreakyEnding"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "moreKaomoji"
        "enable"
      ];
      to = base ++ [
        "moreCommands"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "moreKaomoji"
        "uwuEveryMessage"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEveryMessage"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "moreKaomoji"
        "uwuEverything"
      ];
      to = base ++ [
        "moreCommands"
        "uwuEverything"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # PronounDB -> UserMessagesPronouns
    (lib.modules.doRename {
      from = base ++ [
        "PronounDB"
        "enable"
      ];
      to = base ++ [
        "userMessagesPronouns"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "PronounDB"
        "pronounsFormat"
      ];
      to = base ++ [
        "userMessagesPronouns"
        "pronounsFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "PronounDB"
        "showSelf"
      ];
      to = base ++ [
        "userMessagesPronouns"
        "showSelf"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # RepeatMessage -> RepeatMessages
    (lib.modules.doRename {
      from = base ++ [
        "repeatMessage"
        "enable"
      ];
      to = base ++ [
        "repeatMessages"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # Search -> ReplaceGoogleSearch
    (lib.modules.doRename {
      from = base ++ [
        "search"
        "customEngineName"
      ];
      to = base ++ [
        "replaceGoogleSearch"
        "customEngineName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "search"
        "customEngineURL"
      ];
      to = base ++ [
        "replaceGoogleSearch"
        "customEngineURL"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "search"
        "enable"
      ];
      to = base ++ [
        "replaceGoogleSearch"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "search"
        "replacementEngine"
      ];
      to = base ++ [
        "replaceGoogleSearch"
        "replacementEngine"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # SearchReply -> FullSearchContext
    (lib.modules.doRename {
      from = base ++ [
        "searchReply"
        "enable"
      ];
      to = base ++ [
        "fullSearchContext"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # ShowAllRoles -> AlwaysExpandRoles
    (lib.modules.doRename {
      from = base ++ [
        "showAllRoles"
        "enable"
      ];
      to = base ++ [
        "alwaysExpandRoles"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "showAllRoles"
        "hideArrow"
      ];
      to = base ++ [
        "alwaysExpandRoles"
        "hideArrow"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # StatsfmPresence -> RichPresence
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "absEnabled"
      ];
      to = base ++ [
        "richPresence"
        "absEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "absPassword"
      ];
      to = base ++ [
        "richPresence"
        "absPassword"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "absServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "absServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "absUsername"
      ];
      to = base ++ [
        "richPresence"
        "absUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "enable"
      ];
      to = base ++ [
        "richPresence"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "enabled"
      ];
      to = base ++ [
        "richPresence"
        "enabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "grEnabled"
      ];
      to = base ++ [
        "richPresence"
        "grEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "grRefreshInterval"
      ];
      to = base ++ [
        "richPresence"
        "grRefreshInterval"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfApiKey"
      ];
      to = base ++ [
        "richPresence"
        "jfApiKey"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfCoverType"
      ];
      to = base ++ [
        "richPresence"
        "jfCoverType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfCustomName"
      ];
      to = base ++ [
        "richPresence"
        "jfCustomName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfEnabled"
      ];
      to = base ++ [
        "richPresence"
        "jfEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfEpisodeFormat"
      ];
      to = base ++ [
        "richPresence"
        "jfEpisodeFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfNameDisplay"
      ];
      to = base ++ [
        "richPresence"
        "jfNameDisplay"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfOverrideType"
      ];
      to = base ++ [
        "richPresence"
        "jfOverrideType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfPrivacyMode"
      ];
      to = base ++ [
        "richPresence"
        "jfPrivacyMode"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "jfServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfShowEpisodeName"
      ];
      to = base ++ [
        "richPresence"
        "jfShowEpisodeName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfShowPausedState"
      ];
      to = base ++ [
        "richPresence"
        "jfShowPausedState"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "jfUserId"
      ];
      to = base ++ [
        "richPresence"
        "jfUserId"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbEnabled"
      ];
      to = base ++ [
        "richPresence"
        "lbEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbHideWithActivity"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithActivity"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbMbContact"
      ];
      to = base ++ [
        "richPresence"
        "lbMbContact"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "lbMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "lbNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbShareSong"
      ];
      to = base ++ [
        "richPresence"
        "lbShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbStatusName"
      ];
      to = base ++ [
        "richPresence"
        "lbStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "lbUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbUseLogo"
      ];
      to = base ++ [
        "richPresence"
        "lbUseLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbUseTimeBar"
      ];
      to = base ++ [
        "richPresence"
        "lbUseTimeBar"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "lbUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmAlwaysHideArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmAlwaysHideArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmEnabled"
      ];
      to = base ++ [
        "richPresence"
        "sfmEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmHideWithExternalRpc"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithExternalRpc"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "sfmNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmShareSong"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmShowLogo"
      ];
      to = base ++ [
        "richPresence"
        "sfmShowLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmStatusName"
      ];
      to = base ++ [
        "richPresence"
        "sfmStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "sfmUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "sfmUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statsfmPresence"
        "tosuEnabled"
      ];
      to = base ++ [
        "richPresence"
        "tosuEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # StatusWhilePlaying -> AutoDNDWhilePlaying
    (lib.modules.doRename {
      from = base ++ [
        "statusWhilePlaying"
        "enable"
      ];
      to = base ++ [
        "AutoDNDWhilePlaying"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statusWhilePlaying"
        "excludeInvisible"
      ];
      to = base ++ [
        "AutoDNDWhilePlaying"
        "excludeInvisible"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "statusWhilePlaying"
        "statusToSet"
      ];
      to = base ++ [
        "AutoDNDWhilePlaying"
        "statusToSet"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # TimelessClips -> ClipsEnhancements
    (lib.modules.doRename {
      from = base ++ [
        "timelessClips"
        "enable"
      ];
      to = base ++ [
        "clipsEnhancements"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "timelessClips"
        "enableAdvancedSignals"
      ];
      to = base ++ [
        "clipsEnhancements"
        "enableAdvancedSignals"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "timelessClips"
        "enableScreenshotKeybind"
      ];
      to = base ++ [
        "clipsEnhancements"
        "enableScreenshotKeybind"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "timelessClips"
        "enableSpeakingIndicators"
      ];
      to = base ++ [
        "clipsEnhancements"
        "enableSpeakingIndicators"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "timelessClips"
        "enableVoiceOnlyClips"
      ];
      to = base ++ [
        "clipsEnhancements"
        "enableVoiceOnlyClips"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "timelessClips"
        "ignorePlatformRestriction"
      ];
      to = base ++ [
        "clipsEnhancements"
        "ignorePlatformRestriction"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "timelessClips"
        "richPresenceTagging"
      ];
      to = base ++ [
        "clipsEnhancements"
        "richPresenceTagging"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # TosuRPC -> RichPresence
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "absEnabled"
      ];
      to = base ++ [
        "richPresence"
        "absEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "absPassword"
      ];
      to = base ++ [
        "richPresence"
        "absPassword"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "absServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "absServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "absUsername"
      ];
      to = base ++ [
        "richPresence"
        "absUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "enable"
      ];
      to = base ++ [
        "richPresence"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "enabled"
      ];
      to = base ++ [
        "richPresence"
        "enabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "grEnabled"
      ];
      to = base ++ [
        "richPresence"
        "grEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "grRefreshInterval"
      ];
      to = base ++ [
        "richPresence"
        "grRefreshInterval"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfApiKey"
      ];
      to = base ++ [
        "richPresence"
        "jfApiKey"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfCoverType"
      ];
      to = base ++ [
        "richPresence"
        "jfCoverType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfCustomName"
      ];
      to = base ++ [
        "richPresence"
        "jfCustomName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfEnabled"
      ];
      to = base ++ [
        "richPresence"
        "jfEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfEpisodeFormat"
      ];
      to = base ++ [
        "richPresence"
        "jfEpisodeFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfNameDisplay"
      ];
      to = base ++ [
        "richPresence"
        "jfNameDisplay"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfOverrideType"
      ];
      to = base ++ [
        "richPresence"
        "jfOverrideType"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfPrivacyMode"
      ];
      to = base ++ [
        "richPresence"
        "jfPrivacyMode"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfServerUrl"
      ];
      to = base ++ [
        "richPresence"
        "jfServerUrl"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfShowEpisodeName"
      ];
      to = base ++ [
        "richPresence"
        "jfShowEpisodeName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfShowPausedState"
      ];
      to = base ++ [
        "richPresence"
        "jfShowPausedState"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "jfUserId"
      ];
      to = base ++ [
        "richPresence"
        "jfUserId"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbEnabled"
      ];
      to = base ++ [
        "richPresence"
        "lbEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbHideWithActivity"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithActivity"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "lbHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbMbContact"
      ];
      to = base ++ [
        "richPresence"
        "lbMbContact"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "lbMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "lbNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbShareSong"
      ];
      to = base ++ [
        "richPresence"
        "lbShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbStatusName"
      ];
      to = base ++ [
        "richPresence"
        "lbStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "lbUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbUseLogo"
      ];
      to = base ++ [
        "richPresence"
        "lbUseLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbUseTimeBar"
      ];
      to = base ++ [
        "richPresence"
        "lbUseTimeBar"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "lbUsername"
      ];
      to = base ++ [
        "richPresence"
        "lbUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmAlwaysHideArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmAlwaysHideArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmEnabled"
      ];
      to = base ++ [
        "richPresence"
        "sfmEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmHideWithExternalRpc"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithExternalRpc"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmHideWithSpotify"
      ];
      to = base ++ [
        "richPresence"
        "sfmHideWithSpotify"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmMissingArt"
      ];
      to = base ++ [
        "richPresence"
        "sfmMissingArt"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmNameFormat"
      ];
      to = base ++ [
        "richPresence"
        "sfmNameFormat"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmShareSong"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareSong"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmShareUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmShareUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmShowLogo"
      ];
      to = base ++ [
        "richPresence"
        "sfmShowLogo"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmStatusName"
      ];
      to = base ++ [
        "richPresence"
        "sfmStatusName"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmUseListeningStatus"
      ];
      to = base ++ [
        "richPresence"
        "sfmUseListeningStatus"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "sfmUsername"
      ];
      to = base ++ [
        "richPresence"
        "sfmUsername"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "TosuRPC"
        "tosuEnabled"
      ];
      to = base ++ [
        "richPresence"
        "tosuEnabled"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # YoutubeDescription -> FixYoutubeEmbeds
    (lib.modules.doRename {
      from = base ++ [
        "youtubeDescription"
        "enable"
      ];
      to = base ++ [
        "fixYoutubeEmbeds"
        "enable"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })
    (lib.modules.doRename {
      from = base ++ [
        "youtubeDescription"
        "youtubeDescription"
      ];
      to = base ++ [
        "fixYoutubeEmbeds"
        "youtubeDescription"
      ];
      visible = false;
      warn = false;
      use = x: x;
    })

    # Setting renames: fontLoader
    (lib.modules.doRename {
      from = base ++ [
        "fontLoader"
        "applyOnClodeBlocks"
      ];
      to = base ++ [
        "fontLoader"
        "applyOnCodeBlocks"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: globalBadges
    (lib.modules.doRename {
      from = base ++ [
        "globalBadges"
        "showRa1ncord"
      ];
      to = base ++ [
        "globalBadges"
        "showRaincord"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: noBlockedMessages
    (lib.modules.doRename {
      from = base ++ [
        "noBlockedMessages"
        "ignoreBlockedMessages"
      ];
      to = base ++ [
        "noBlockedMessages"
        "ignoreMessages"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: platformIndicators
    (lib.modules.doRename {
      from = base ++ [
        "platformIndicators"
        "badges"
      ];
      to = base ++ [
        "platformIndicators"
        "profiles"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

  ];
}
