# This file is auto-generated by @nixcord/nix-generator
# DO NOT EDIT this file directly; instead update the generator

{ lib, ... }:
let
  base = [
    "programs"
    "nixcord"
    "config"
    "plugins"
  ];
in
{
  imports = [
    # Anammox -> Declutter
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "alwaysShowUsername"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "alwaysShowUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "enable"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeAudioMenus"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeAudioMenus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeAvatarDecoration"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeAvatarDecoration"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeBillingSettings"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeBillingSettings"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeButtonTooltips"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeButtonTooltips"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeClanTag"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeClanTag"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeGiftButton"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeGiftButton"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeNameplate"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeNameplate"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeProfileEffect"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeProfileEffect"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeQuestsAboveDM"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeQuestsAboveDM"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeServerBoostInfo"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeServerBoostInfo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeShopAboveDM"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeShopAboveDM"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "anammox"
          "removeUnavailableEmojiPicker"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeUnavailableEmojiPicker"
        ]
      )
    )

    # AudioBookShelfRichPresence -> RichPresence
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "absEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "absPassword"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absPassword"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "absServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "absUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "enable"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "enabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "grEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "grRefreshInterval"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grRefreshInterval"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfApiKey"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfApiKey"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfCoverType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCoverType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfCustomName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCustomName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfEpisodeFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEpisodeFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfNameDisplay"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfNameDisplay"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfOverrideType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfOverrideType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfPrivacyMode"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfPrivacyMode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfShowEpisodeName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowEpisodeName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfShowPausedState"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowPausedState"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "jfUserId"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfUserId"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbHideWithActivity"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithActivity"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbMbContact"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMbContact"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbUseLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbUseTimeBar"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseTimeBar"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "lbUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmAlwaysHideArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmAlwaysHideArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmHideWithExternalRpc"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithExternalRpc"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmShowLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShowLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "sfmUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "audioBookShelfRichPresence"
          "tosuEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "tosuEnabled"
        ]
      )
    )

    # BetterQuickReact -> MoreQuickReactions
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterQuickReact"
          "columns"
        ]
      )
      (
        base
        ++ [
          "moreQuickReactions"
          "columns"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterQuickReact"
          "compactMode"
        ]
      )
      (
        base
        ++ [
          "moreQuickReactions"
          "compactMode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterQuickReact"
          "enable"
        ]
      )
      (
        base
        ++ [
          "moreQuickReactions"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterQuickReact"
          "frequentEmojis"
        ]
      )
      (
        base
        ++ [
          "moreQuickReactions"
          "frequentEmojis"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterQuickReact"
          "reactionCount"
        ]
      )
      (
        base
        ++ [
          "moreQuickReactions"
          "reactionCount"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterQuickReact"
          "rows"
        ]
      )
      (
        base
        ++ [
          "moreQuickReactions"
          "rows"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterQuickReact"
          "scroll"
        ]
      )
      (
        base
        ++ [
          "moreQuickReactions"
          "scroll"
        ]
      )
    )

    # BetterUserArea -> Declutter
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "alwaysShowUsername"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "alwaysShowUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "enable"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeAudioMenus"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeAudioMenus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeAvatarDecoration"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeAvatarDecoration"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeBillingSettings"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeBillingSettings"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeButtonTooltips"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeButtonTooltips"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeClanTag"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeClanTag"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeGiftButton"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeGiftButton"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeNameplate"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeNameplate"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeProfileEffect"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeProfileEffect"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeQuestsAboveDM"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeQuestsAboveDM"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeServerBoostInfo"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeServerBoostInfo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeShopAboveDM"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeShopAboveDM"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "betterUserArea"
          "removeUnavailableEmojiPicker"
        ]
      )
      (
        base
        ++ [
          "declutter"
          "removeUnavailableEmojiPicker"
        ]
      )
    )

    # EmoteCloner -> ExpressionCloner
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "emoteCloner"
          "enable"
        ]
      )
      (
        base
        ++ [
          "expressionCloner"
          "enable"
        ]
      )
    )

    # FriendCloud -> MoreCommands
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "friendCloud"
          "addFreakyEnding"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "addFreakyEnding"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "friendCloud"
          "enable"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "friendCloud"
          "uwuEveryMessage"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEveryMessage"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "friendCloud"
          "uwuEverything"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEverything"
        ]
      )
    )

    # GensokyoRadioRPC -> RichPresence
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "absEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "absPassword"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absPassword"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "absServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "absUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "enable"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "enabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "grEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "grRefreshInterval"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grRefreshInterval"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfApiKey"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfApiKey"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfCoverType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCoverType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfCustomName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCustomName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfEpisodeFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEpisodeFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfNameDisplay"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfNameDisplay"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfOverrideType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfOverrideType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfPrivacyMode"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfPrivacyMode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfShowEpisodeName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowEpisodeName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfShowPausedState"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowPausedState"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "jfUserId"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfUserId"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbHideWithActivity"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithActivity"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbMbContact"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMbContact"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbUseLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbUseTimeBar"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseTimeBar"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "lbUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmAlwaysHideArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmAlwaysHideArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmHideWithExternalRpc"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithExternalRpc"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmShowLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShowLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "sfmUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "GensokyoRadioRPC"
          "tosuEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "tosuEnabled"
        ]
      )
    )

    # GifRoulette -> MoreCommands
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "gifRoulette"
          "addFreakyEnding"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "addFreakyEnding"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "gifRoulette"
          "enable"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "gifRoulette"
          "uwuEveryMessage"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEveryMessage"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "gifRoulette"
          "uwuEverything"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEverything"
        ]
      )
    )

    # HideAttachments -> HideMedia
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "hideAttachments"
          "enable"
        ]
      )
      (
        base
        ++ [
          "hideMedia"
          "enable"
        ]
      )
    )

    # ImgToGif -> MoreCommands
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "imgToGif"
          "addFreakyEnding"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "addFreakyEnding"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "imgToGif"
          "enable"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "imgToGif"
          "uwuEveryMessage"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEveryMessage"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "imgToGif"
          "uwuEverything"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEverything"
        ]
      )
    )

    # JellyfinRichPresence -> RichPresence
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "absEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "absPassword"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absPassword"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "absServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "absUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "enable"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "enabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "grEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "grRefreshInterval"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grRefreshInterval"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfApiKey"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfApiKey"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfCoverType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCoverType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfCustomName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCustomName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfEpisodeFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEpisodeFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfNameDisplay"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfNameDisplay"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfOverrideType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfOverrideType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfPrivacyMode"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfPrivacyMode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfShowEpisodeName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowEpisodeName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfShowPausedState"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowPausedState"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "jfUserId"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfUserId"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbHideWithActivity"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithActivity"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbMbContact"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMbContact"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbUseLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbUseTimeBar"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseTimeBar"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "lbUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmAlwaysHideArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmAlwaysHideArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmHideWithExternalRpc"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithExternalRpc"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmShowLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShowLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "sfmUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "jellyfinRichPresence"
          "tosuEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "tosuEnabled"
        ]
      )
    )

    # ListenBrainzRPC -> RichPresence
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "absEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "absPassword"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absPassword"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "absServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "absUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "enable"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "enabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "grEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "grRefreshInterval"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grRefreshInterval"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfApiKey"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfApiKey"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfCoverType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCoverType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfCustomName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCustomName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfEpisodeFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEpisodeFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfNameDisplay"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfNameDisplay"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfOverrideType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfOverrideType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfPrivacyMode"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfPrivacyMode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfShowEpisodeName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowEpisodeName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfShowPausedState"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowPausedState"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "jfUserId"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfUserId"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbHideWithActivity"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithActivity"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbMbContact"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMbContact"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbUseLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbUseTimeBar"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseTimeBar"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "lbUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmAlwaysHideArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmAlwaysHideArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmHideWithExternalRpc"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithExternalRpc"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmShowLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShowLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "sfmUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "ListenBrainzRPC"
          "tosuEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "tosuEnabled"
        ]
      )
    )

    # MemberListActivities -> BetterActivities
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "allActivitiesStyle"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "allActivitiesStyle"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "enable"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "hideTooltip"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "hideTooltip"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "iconSize"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "iconSize"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "memberList"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "memberList"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "removeGameActivityStatus"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "removeGameActivityStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "renderGifs"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "renderGifs"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "specialFirst"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "specialFirst"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "memberListActivities"
          "userPopout"
        ]
      )
      (
        base
        ++ [
          "betterActivities"
          "userPopout"
        ]
      )
    )

    # MessageTags -> CustomCommands
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "messageTags"
          "enable"
        ]
      )
      (
        base
        ++ [
          "customCommands"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "messageTags"
          "tagsList"
        ]
      )
      (
        base
        ++ [
          "customCommands"
          "tagsList"
        ]
      )
    )

    # MoreKaomoji -> MoreCommands
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "moreKaomoji"
          "addFreakyEnding"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "addFreakyEnding"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "moreKaomoji"
          "enable"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "moreKaomoji"
          "uwuEveryMessage"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEveryMessage"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "moreKaomoji"
          "uwuEverything"
        ]
      )
      (
        base
        ++ [
          "moreCommands"
          "uwuEverything"
        ]
      )
    )

    # PronounDB -> UserMessagesPronouns
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "PronounDB"
          "enable"
        ]
      )
      (
        base
        ++ [
          "userMessagesPronouns"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "PronounDB"
          "pronounsFormat"
        ]
      )
      (
        base
        ++ [
          "userMessagesPronouns"
          "pronounsFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "PronounDB"
          "showSelf"
        ]
      )
      (
        base
        ++ [
          "userMessagesPronouns"
          "showSelf"
        ]
      )
    )

    # RepeatMessage -> RepeatMessages
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "repeatMessage"
          "enable"
        ]
      )
      (
        base
        ++ [
          "repeatMessages"
          "enable"
        ]
      )
    )

    # Search -> ReplaceGoogleSearch
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "search"
          "customEngineName"
        ]
      )
      (
        base
        ++ [
          "replaceGoogleSearch"
          "customEngineName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "search"
          "customEngineURL"
        ]
      )
      (
        base
        ++ [
          "replaceGoogleSearch"
          "customEngineURL"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "search"
          "enable"
        ]
      )
      (
        base
        ++ [
          "replaceGoogleSearch"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "search"
          "replacementEngine"
        ]
      )
      (
        base
        ++ [
          "replaceGoogleSearch"
          "replacementEngine"
        ]
      )
    )

    # SearchReply -> FullSearchContext
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "searchReply"
          "enable"
        ]
      )
      (
        base
        ++ [
          "fullSearchContext"
          "enable"
        ]
      )
    )

    # ShowAllRoles -> AlwaysExpandRoles
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "showAllRoles"
          "enable"
        ]
      )
      (
        base
        ++ [
          "alwaysExpandRoles"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "showAllRoles"
          "hideArrow"
        ]
      )
      (
        base
        ++ [
          "alwaysExpandRoles"
          "hideArrow"
        ]
      )
    )

    # StatsfmPresence -> RichPresence
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "absEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "absPassword"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absPassword"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "absServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "absUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "enable"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "enabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "grEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "grRefreshInterval"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grRefreshInterval"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfApiKey"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfApiKey"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfCoverType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCoverType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfCustomName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCustomName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfEpisodeFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEpisodeFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfNameDisplay"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfNameDisplay"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfOverrideType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfOverrideType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfPrivacyMode"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfPrivacyMode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfShowEpisodeName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowEpisodeName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfShowPausedState"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowPausedState"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "jfUserId"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfUserId"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbHideWithActivity"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithActivity"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbMbContact"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMbContact"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbUseLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbUseTimeBar"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseTimeBar"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "lbUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmAlwaysHideArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmAlwaysHideArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmHideWithExternalRpc"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithExternalRpc"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmShowLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShowLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "sfmUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statsfmPresence"
          "tosuEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "tosuEnabled"
        ]
      )
    )

    # StatusWhilePlaying -> AutoDNDWhilePlaying
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statusWhilePlaying"
          "enable"
        ]
      )
      (
        base
        ++ [
          "AutoDNDWhilePlaying"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statusWhilePlaying"
          "excludeInvisible"
        ]
      )
      (
        base
        ++ [
          "AutoDNDWhilePlaying"
          "excludeInvisible"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "statusWhilePlaying"
          "statusToSet"
        ]
      )
      (
        base
        ++ [
          "AutoDNDWhilePlaying"
          "statusToSet"
        ]
      )
    )

    # TimelessClips -> ClipsEnhancements
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "timelessClips"
          "enable"
        ]
      )
      (
        base
        ++ [
          "clipsEnhancements"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "timelessClips"
          "enableAdvancedSignals"
        ]
      )
      (
        base
        ++ [
          "clipsEnhancements"
          "enableAdvancedSignals"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "timelessClips"
          "enableScreenshotKeybind"
        ]
      )
      (
        base
        ++ [
          "clipsEnhancements"
          "enableScreenshotKeybind"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "timelessClips"
          "enableSpeakingIndicators"
        ]
      )
      (
        base
        ++ [
          "clipsEnhancements"
          "enableSpeakingIndicators"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "timelessClips"
          "enableVoiceOnlyClips"
        ]
      )
      (
        base
        ++ [
          "clipsEnhancements"
          "enableVoiceOnlyClips"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "timelessClips"
          "ignorePlatformRestriction"
        ]
      )
      (
        base
        ++ [
          "clipsEnhancements"
          "ignorePlatformRestriction"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "timelessClips"
          "richPresenceTagging"
        ]
      )
      (
        base
        ++ [
          "clipsEnhancements"
          "richPresenceTagging"
        ]
      )
    )

    # TosuRPC -> RichPresence
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "absEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "absPassword"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absPassword"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "absServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "absUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "absUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "enable"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "enabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "enabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "grEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "grRefreshInterval"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "grRefreshInterval"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfApiKey"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfApiKey"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfCoverType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCoverType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfCustomName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfCustomName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfEpisodeFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfEpisodeFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfNameDisplay"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfNameDisplay"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfOverrideType"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfOverrideType"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfPrivacyMode"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfPrivacyMode"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfServerUrl"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfServerUrl"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfShowEpisodeName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowEpisodeName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfShowPausedState"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfShowPausedState"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "jfUserId"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "jfUserId"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbHideWithActivity"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithActivity"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbMbContact"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMbContact"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbUseLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbUseTimeBar"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUseTimeBar"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "lbUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "lbUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmAlwaysHideArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmAlwaysHideArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmEnabled"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmHideWithExternalRpc"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithExternalRpc"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmHideWithSpotify"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmHideWithSpotify"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmMissingArt"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmMissingArt"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmNameFormat"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmNameFormat"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmShareSong"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareSong"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmShareUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShareUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmShowLogo"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmShowLogo"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmStatusName"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmStatusName"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmUseListeningStatus"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUseListeningStatus"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "sfmUsername"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "sfmUsername"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "TosuRPC"
          "tosuEnabled"
        ]
      )
      (
        base
        ++ [
          "richPresence"
          "tosuEnabled"
        ]
      )
    )

    # YoutubeDescription -> FixYoutubeEmbeds
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "youtubeDescription"
          "enable"
        ]
      )
      (
        base
        ++ [
          "fixYoutubeEmbeds"
          "enable"
        ]
      )
    )
    (lib.modules.mkRenamedOptionModule
      (
        base
        ++ [
          "youtubeDescription"
          "youtubeDescription"
        ]
      )
      (
        base
        ++ [
          "fixYoutubeEmbeds"
          "youtubeDescription"
        ]
      )
    )

    # Setting renames: fontLoader
    (lib.modules.doRename {
      from = base ++ [
        "fontLoader"
        "applyOnClodeBlocks"
      ];
      to = base ++ [
        "fontLoader"
        "applyOnCodeBlocks"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: globalBadges
    (lib.modules.doRename {
      from = base ++ [
        "globalBadges"
        "showRa1ncord"
      ];
      to = base ++ [
        "globalBadges"
        "showRaincord"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: noBlockedMessages
    (lib.modules.doRename {
      from = base ++ [
        "noBlockedMessages"
        "ignoreBlockedMessages"
      ];
      to = base ++ [
        "noBlockedMessages"
        "ignoreMessages"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

    # Setting renames: platformIndicators
    (lib.modules.doRename {
      from = base ++ [
        "platformIndicators"
        "badges"
      ];
      to = base ++ [
        "platformIndicators"
        "profiles"
      ];
      visible = false;
      warn = true;
      use = x: x;
    })

  ];
}
